import { Router } from 'express';
import { ProjectStatus, Role } from '@prisma/client';
import { z } from 'zod';
import { authenticate, allow, officers } from '../middleware/auth.js';
import { upload } from '../middleware/upload.js';
import { validate } from '../middleware/validate.js';
import { audit } from '../utils/audit.js';
import { ApiError, asyncHandler, ok } from '../utils/http.js';
import { prisma } from '../utils/prisma.js';
import { recalculateProject } from '../services/risk.service.js';

const router = Router();
const projectInput = z.object({ projectCode: z.string().min(3).max(40), name: z.string().min(3).max(200), description: z.string().min(10), location: z.string().min(2), latitude: z.coerce.number().gte(6).lte(38), longitude: z.coerce.number().gte(68).lte(98), budget: z.coerce.number().positive(), spentAmount: z.coerce.number().nonnegative().optional(), contractor: z.string().max(200).optional().nullable(), startDate: z.coerce.date(), expectedCompletion: z.coerce.date(), actualCompletion: z.coerce.date().optional().nullable(), progress: z.coerce.number().int().min(0).max(100).optional(), ministryId: z.string(), departmentId: z.string(), schemeId: z.string().optional().nullable(), stateId: z.string(), districtId: z.string(), publicVisible: z.coerce.boolean().optional() });
const listQuery = z.object({ q: z.string().optional(), page: z.coerce.number().int().positive().default(1), limit: z.coerce.number().int().min(1).max(100).default(12), status: z.nativeEnum(ProjectStatus).optional(), stateId: z.string().optional(), districtId: z.string().optional(), departmentId: z.string().optional(), ministryId: z.string().optional(), schemeId: z.string().optional(), sortBy: z.enum(['name','createdAt','progress','budget','riskScore']).default('createdAt'), sortOrder: z.enum(['asc','desc']).default('desc') });
const include = { ministry: { select: { id: true, name: true } }, department: { select: { id: true, name: true } }, scheme: { select: { id: true, name: true } }, state: { select: { id: true, name: true } }, district: { select: { id: true, name: true } } } as const;
const adminRoles = [Role.SUPER_ADMIN, Role.ADMIN];

router.get('/', validate(listQuery, 'query'), asyncHandler(async (req, res) => {
  const { q, page, limit, status, stateId, districtId, departmentId, ministryId, schemeId, sortBy, sortOrder } = req.query as z.infer<typeof listQuery>;
  const where = { publicVisible: true, ...(status ? { status } : {}), ...(stateId ? { stateId } : {}), ...(districtId ? { districtId } : {}), ...(departmentId ? { departmentId } : {}), ...(ministryId ? { ministryId } : {}), ...(schemeId ? { schemeId } : {}), ...(q ? { OR: [{ projectCode: { contains: q, mode: 'insensitive' as const } }, { name: { contains: q, mode: 'insensitive' as const } }, { location: { contains: q, mode: 'insensitive' as const } }, { ministry: { name: { contains: q, mode: 'insensitive' as const } } }, { department: { name: { contains: q, mode: 'insensitive' as const } } }, { scheme: { name: { contains: q, mode: 'insensitive' as const } } }] } : {}) };
  const [items, total] = await Promise.all([prisma.project.findMany({ where, include, orderBy: { [sortBy]: sortOrder }, skip: (page - 1) * limit, take: limit }), prisma.project.count({ where })]);
  ok(res, { items, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
}));
router.get('/lookups', asyncHandler(async (_req, res) => {
  const [ministries, departments, schemes, states, districts] = await Promise.all([prisma.ministry.findMany({ orderBy: { name: 'asc' } }), prisma.department.findMany({ orderBy: { name: 'asc' } }), prisma.scheme.findMany({ orderBy: { name: 'asc' } }), prisma.state.findMany({ orderBy: { name: 'asc' } }), prisma.district.findMany({ orderBy: { name: 'asc' } })]);
  ok(res, { ministries, departments, schemes, states, districts });
}));
router.get('/:id', asyncHandler(async (req, res) => {
  const project = await prisma.project.findFirst({ where: { OR: [{ id: req.params.id }, { projectCode: req.params.id }], publicVisible: true }, include: { ...include, milestones: { orderBy: { plannedDate: 'asc' } }, updates: { where: { isPublic: true }, orderBy: { createdAt: 'desc' }, take: 20, include: { author: { select: { name: true } } } }, evidence: { where: { isPublic: true }, orderBy: { createdAt: 'desc' }, select: { id: true, fileName: true, mimeType: true, size: true, description: true, createdAt: true } } } });
  if (!project) throw new ApiError(404, 'Project not found', 'NOT_FOUND'); ok(res, project);
}));
router.get('/:id/internal', authenticate, asyncHandler(async (req, res) => {
  const project = await prisma.project.findUnique({ where: { id: req.params.id }, include: { ...include, milestones: { orderBy: { plannedDate: 'asc' } }, issues: { orderBy: { createdAt: 'desc' }, include: { assignedTo: { select: { id: true, name: true, email: true } }, reportedBy: { select: { id: true, name: true } } } }, evidence: { orderBy: { createdAt: 'desc' }, include: { uploadedBy: { select: { id: true, name: true } } } }, updates: { orderBy: { createdAt: 'desc' }, include: { author: { select: { name: true } } } } } });
  if (!project) throw new ApiError(404, 'Project not found', 'NOT_FOUND'); ok(res, project);
}));
router.post('/', authenticate, allow(...adminRoles, Role.MINISTRY_OFFICER, Role.STATE_OFFICER), validate(projectInput), asyncHandler(async (req, res) => {
  const body = req.body as z.infer<typeof projectInput>; if (body.expectedCompletion <= body.startDate) throw new ApiError(400, 'Expected completion must be after start date', 'INVALID_DATES');
  const project = await prisma.$transaction(async tx => { const created = await tx.project.create({ data: { ...body, createdById: req.user!.id, spentAmount: body.spentAmount ?? 0, progress: body.progress ?? 0 } }); await tx.auditLog.create({ data: { userId: req.user!.id, action: 'CREATE', entity: 'Project', entityId: created.id, newValue: { projectCode: created.projectCode, name: created.name }, ipAddress: req.ip } }); return created; });
  await recalculateProject(project.id); ok(res, await prisma.project.findUnique({ where: { id: project.id }, include }), 'Project created successfully', 201);
}));
router.put('/:id', authenticate, allow(...adminRoles, Role.MINISTRY_OFFICER, Role.STATE_OFFICER), validate(projectInput.partial()), asyncHandler(async (req, res) => {
  const old = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!old) throw new ApiError(404, 'Project not found', 'NOT_FOUND');
  const body = req.body as Partial<z.infer<typeof projectInput>>; const project = await prisma.$transaction(async tx => { const updated = await tx.project.update({ where: { id: old.id }, data: body }); await tx.auditLog.create({ data: { userId: req.user!.id, action: 'UPDATE', entity: 'Project', entityId: old.id, oldValue: { progress: old.progress, status: old.status }, newValue: body, ipAddress: req.ip } }); return updated; });
  await recalculateProject(project.id); ok(res, await prisma.project.findUnique({ where: { id: project.id }, include }), 'Project updated successfully');
}));
router.patch('/:id/progress', authenticate, allow(...officers), validate(z.object({ progress: z.coerce.number().int().min(0).max(100), message: z.string().min(4).max(1000), isPublic: z.coerce.boolean().default(true) })), asyncHandler(async (req, res) => {
  const old = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!old) throw new ApiError(404, 'Project not found', 'NOT_FOUND'); const body = req.body;
  await prisma.$transaction(async tx => { await tx.project.update({ where: { id: old.id }, data: { progress: body.progress, actualCompletion: body.progress === 100 ? new Date() : undefined } }); await tx.projectUpdate.create({ data: { projectId: old.id, authorId: req.user!.id, progress: body.progress, message: body.message, isPublic: body.isPublic } }); await tx.auditLog.create({ data: { userId: req.user!.id, action: 'PROGRESS_UPDATE', entity: 'Project', entityId: old.id, oldValue: { progress: old.progress }, newValue: { progress: body.progress }, ipAddress: req.ip } }); });
  const project = await recalculateProject(old.id); ok(res, project, 'Project progress updated and risk recalculated');
}));
router.patch('/:id/status-override', authenticate, allow(...adminRoles), validate(z.object({ status: z.nativeEnum(ProjectStatus).nullable() })), asyncHandler(async (req, res) => {
  const project = await prisma.project.update({ where: { id: req.params.id }, data: { manualStatusOverride: req.body.status, ...(req.body.status ? { status: req.body.status } : {}) } }); await audit({ userId: req.user!.id, action: 'STATUS_OVERRIDE', entity: 'Project', entityId: project.id, newValue: { manualStatusOverride: req.body.status }, ipAddress: req.ip }); if (!req.body.status) await recalculateProject(project.id); ok(res, project, 'Status override updated');
}));
router.delete('/:id', authenticate, allow(...adminRoles), asyncHandler(async (req, res) => { const project = await prisma.project.findUnique({ where: { id: req.params.id } }); if (!project) throw new ApiError(404, 'Project not found', 'NOT_FOUND'); await prisma.$transaction([prisma.project.delete({ where: { id: project.id } }), prisma.auditLog.create({ data: { userId: req.user!.id, action: 'DELETE', entity: 'Project', entityId: project.id, oldValue: { name: project.name, projectCode: project.projectCode }, ipAddress: req.ip } })]); ok(res, null, 'Project deleted successfully'); }));
router.get('/:id/milestones', asyncHandler(async (req, res) => ok(res, await prisma.milestone.findMany({ where: { projectId: req.params.id }, orderBy: { plannedDate: 'asc' } }))));
router.post('/:id/milestones', authenticate, allow(...officers), validate(z.object({ name: z.string().min(3), description: z.string().optional(), plannedDate: z.coerce.date(), actualDate: z.coerce.date().optional().nullable(), progress: z.coerce.number().int().min(0).max(100).default(0), status: z.enum(['PENDING','IN_PROGRESS','COMPLETED','DELAYED']).default('PENDING') })), asyncHandler(async (req, res) => { const milestone = await prisma.milestone.create({ data: { ...req.body, projectId: req.params.id } }); await audit({ userId: req.user!.id, action: 'CREATE', entity: 'Milestone', entityId: milestone.id, newValue: req.body, ipAddress: req.ip }); await recalculateProject(req.params.id); ok(res, milestone, 'Milestone created', 201); }));
router.put('/milestones/:milestoneId', authenticate, allow(...officers), validate(z.object({ name: z.string().min(3).optional(), description: z.string().optional().nullable(), plannedDate: z.coerce.date().optional(), actualDate: z.coerce.date().optional().nullable(), progress: z.coerce.number().int().min(0).max(100).optional(), status: z.enum(['PENDING','IN_PROGRESS','COMPLETED','DELAYED']).optional() })), asyncHandler(async (req, res) => { const old = await prisma.milestone.findUnique({ where: { id: req.params.milestoneId } }); if (!old) throw new ApiError(404, 'Milestone not found', 'NOT_FOUND'); const m = await prisma.milestone.update({ where: { id: old.id }, data: req.body }); await audit({ userId: req.user!.id, action: 'UPDATE', entity: 'Milestone', entityId: m.id, oldValue: { status: old.status }, newValue: req.body, ipAddress: req.ip }); await recalculateProject(m.projectId); ok(res, m, 'Milestone updated'); }));
router.delete('/milestones/:milestoneId', authenticate, allow(...officers), asyncHandler(async (req, res) => { const milestone = await prisma.milestone.findUnique({ where: { id: req.params.milestoneId } }); if (!milestone) throw new ApiError(404, 'Milestone not found', 'NOT_FOUND'); await prisma.milestone.delete({ where: { id: milestone.id } }); await audit({ userId: req.user!.id, action: 'DELETE', entity: 'Milestone', entityId: milestone.id, ipAddress: req.ip }); await recalculateProject(milestone.projectId); ok(res, null, 'Milestone deleted'); }));
router.get('/:id/evidence', authenticate, asyncHandler(async (req, res) => ok(res, await prisma.evidence.findMany({ where: { projectId: req.params.id }, include: { uploadedBy: { select: { name: true } } }, orderBy: { createdAt: 'desc' } }))));
router.post('/:id/evidence', authenticate, allow(...officers), upload.array('files', 5), asyncHandler(async (req, res) => { const files = req.files as Express.Multer.File[]; if (!files?.length) throw new ApiError(400, 'At least one supported file is required', 'FILE_REQUIRED'); const saved = await prisma.$transaction(files.map(file => prisma.evidence.create({ data: { projectId: req.params.id, fileName: file.originalname, storedName: file.filename, mimeType: file.mimetype, size: file.size, description: typeof req.body.description === 'string' ? req.body.description : null, isPublic: req.body.isPublic === 'true', uploadedById: req.user!.id } }))); for (const evidence of saved) await audit({ userId: req.user!.id, action: 'UPLOAD', entity: 'Evidence', entityId: evidence.id, newValue: { fileName: evidence.fileName }, ipAddress: req.ip }); ok(res, saved, 'Evidence uploaded successfully', 201); }));
router.delete('/evidence/:evidenceId', authenticate, allow(...officers), asyncHandler(async (req, res) => { const evidence = await prisma.evidence.findUnique({ where: { id: req.params.evidenceId } }); if (!evidence) throw new ApiError(404, 'Evidence not found', 'NOT_FOUND'); await prisma.evidence.delete({ where: { id: evidence.id } }); await audit({ userId: req.user!.id, action: 'DELETE', entity: 'Evidence', entityId: evidence.id, ipAddress: req.ip }); ok(res, null, 'Evidence record deleted'); }));
router.get('/:id/updates', asyncHandler(async (req, res) => ok(res, await prisma.projectUpdate.findMany({ where: { projectId: req.params.id, isPublic: true }, include: { author: { select: { name: true } } }, orderBy: { createdAt: 'desc' } }))));
router.post('/:id/updates', authenticate, allow(...officers), validate(z.object({ progress: z.coerce.number().int().min(0).max(100), message: z.string().min(4), isPublic: z.coerce.boolean().default(true) })), asyncHandler(async (req, res) => { const u = await prisma.projectUpdate.create({ data: { ...req.body, projectId: req.params.id, authorId: req.user!.id } }); await audit({ userId: req.user!.id, action: 'CREATE', entity: 'ProjectUpdate', entityId: u.id, ipAddress: req.ip }); ok(res, u, 'Project update published', 201); }));
export default router;
